# fly.toml app configuration file generated for custom-cover-letter on 2024-11-13T13:51:13+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'custom-cover-letter'
primary_region = 'mad'

[build]

# [http_service]
#   internal_port = 3000
#   force_https = true
#   auto_stop_machines = 'stop'
#   auto_start_machines = true
#   min_machines_running = 0
#   processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
